name: HardcoreTabs
main: io.github.ye7i.hardcore_tabs.HardcoreTabs 
version: 0.001a

commands:
  test:
    description: Test command
    usage: /test
  bcast:
    description: Broadcast
    usage: /broadcast <argument>