name: HardcoreTabs
main: io.github.ye7i.hardcore_tabs.HardcoreTabs 
version: 1.01(Narwhal)

permissions:
  hardcoretabs.all:
    description: Allows access to all Hardcore Tabs features excluding commands.
    children:
      hardcoretabs.tablist: true
      hardcoretabs.nametags: true
  hardcoretabs.reload:
    description: Allows you to reload the Hardcore Tabs plugin config.
    default: op
  hardcoretabs.tablist:
    description: Allows a group to take on Hardcore Tabs settings for the tab list.
    default: false
  hardcoretabs.nametags:
    description: Allows a group to take on Hardcore Tabs settings for player name tags.
    default: false

commands:
  hctreload:
    description: Reload the HardcoreTabs config file. This is useful when you don't want to reload the entire server.
    usage: /hctreload
    permission: hardcoretabs.reload
    permission-message: You do not have the required permissions to use this command.